### ISSUE TITLE
How to use package without installing?

### ISSUE THREAD

**Issue by wxguy** [pratiman-91/colormaps#10]
This issue is relevant to the issue mentioned at https://github.com/pratiman-91/colormaps/issues/8. Due to a conflict with `PySide6` and `colormaps`, I could not use your package. Request you suggest a way to use it without installing it.

**Comment by pratiman-91** [comment]
@wxguy I am looking into the issue.

**Comment by pratiman-91** [comment]
You can try using the development version using:
```python
git clone https://github.com/pratiman-91/colormaps.git
cd colormaps
python setup.py install
```

**Comment by wxguy** [comment]
`python setup.py install`. 

Is there any advantage of using this method over pip? I would like to keep the package next to my own script/ application and start importing. This is what I am looking at.

**Comment by pratiman-91** [comment]
It is important to use `setup.py` at least the first time as it will dynamically generate the whole package. If you skip this step things might not work as expected.

I hope this explains.
