### ISSUE TITLE
Incompatibility with `matplotlib` versions from 3.9.0 going forward

### ISSUE THREAD

**Issue by FlorianSchreiner1** [pratiman-91/colormaps#11]
Due to changes in the `matplotlib` API (see https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.9.0.html#top-level-cmap-registration-and-access-functions-in-mpl-cm) the `colormaps` package is incompatible with `matplotlib` versions 3.9.0 and above.
Trying to use the `colormaps` package results in the following error: `AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'` because of the aformentioned API change.

Tested with `matplotlib` versions 3.8.4 (no error is thrown) and 3.9.0 (the error exists).

**Comment by pratiman-91** [comment]
Thanks for submitting the issue. I will take a look and update next week.

**Comment by pratiman-91** [comment]
Updated to be used with latest matplotlib 3.9.0 onwards.
