### ISSUE TITLE
Upload the package to conda-forge

### ISSUE THREAD

**Issue by wxguy** [pratiman-91/colormaps#2]
Good work needs to be utilised by many. Please upload your package to `conda-forge`.

**Comment by pratiman-91** [comment]
@wxguy Yes, I am planning to, but not getting enough time to work on this for a long time.

**Comment by wxguy** [comment]
Are you still in the planning stage (since Jan 2023)? :-)

Just thought of head-up.

**Comment by pratiman-91** [comment]
Got busy with other stuff... I have started working on it and in the upcoming weeks it should be on `conda-forge`.

**Comment by pratiman-91** [comment]
it is now available in `conda-forge`.

you can install the package using `conda install colormaps -c conda-forge` or using `mamba install colormaps`.
