### ISSUE TITLE
Upload colormaps package to PyPi for helping in automation

### ISSUE THREAD

**Issue by wxguy** [pratiman-91/colormaps#4]
This is relevant to issue mentioned at `https://github.com/pratiman-91/colormaps/issues/2`. Can you please upload the package to PyPi? I am sure that this would put you one step closer to making package for conda-forge.

It is difficult to make the package install in automated mode for my project. I am sure that it does not make much time to upload to PyPi as you are already using setup.py.

**Comment by pratiman-91** [comment]
I have uploaded it to PyPi. I hope this helps!
https://pypi.org/project/colormaps/
