### ISSUE TITLE
Incompatabilities between PySide6 and colormaps

### ISSUE THREAD

**Issue by wxguy** [pratiman-91/colormaps#8]
I have a script that uses both GUI and the command line. When I use the script to be used as only the command line, it works without an issue. However, when invoking GUI which is based on PySide6, it produces the following error.

```
import colormaps as cmaps
  File "shibokensupport/signature/loader.py", line 61, in feature_imported
  File "shibokensupport/feature.py", line 135, in feature_imported
AttributeError: 'Cmaps' object has no attribute '__name__'
```

Not able to figure out what went wrong. Can you please help me out on this...

**Comment by pratiman-91** [comment]
@wxguy 
I am not aware of this script that you are using.

**Comment by wxguy** [comment]
In continuation of the above conversation, this is what I get when I install the colormaps package with `pip`:

```
pip install colormaps
WARNING: Skipping /home/sundar/miniconda/envs/test/lib/python3.11/site-packages/PySide6-6.5.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /home/sundar/miniconda/envs/test/lib/python3.11/site-packages/shiboken6-6.5.1.dist-info due to invalid metadata entry 'name'
.
.
.
WARNING: Skipping /home/sundar/miniconda/envs/test/lib/python3.11/site-packages/PySide6-6.5.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /home/sundar/miniconda/envs/test/lib/python3.11/site-packages/shiboken6-6.5.1.dist-info due to invalid metadata entry 'name'
Installing collected packages: colormaps
WARNING: Skipping /home/sundar/miniconda/envs/test/lib/python3.11/site-packages/PySide6-6.5.1.dist-info due to invalid metadata entry 'name'
WARNING: Skipping /home/sundar/miniconda/envs/test/lib/python3.11/site-packages/shiboken6-6.5.1.dist-info due to invalid metadata entry 'name'
Successfully installed colormaps-0.4.0
```

This may be useful for debugging purposes. I did a pip install within the conda environment.

**Comment by pratiman-91** [comment]
@wxguy I am still unable to replicate your problem. I suggest you create a new environment using `conda` and install only `PySide6` and then `colormaps` using `pip`. And if there is a problem then report it back. I can look into it.

**Comment by wxguy** [comment]
> @wxguy I am still unable to replicate your problem. I suggest you create a new environment using `conda` and install only `PySide6` and then `colormaps` using `pip`. And if there is a problem then report it back. I can look into it.

This is what I exactly did so. Will forward my environment file shortly. Suggest you to include your package as part of conda distribution. Since you already has pypi, I am sure that it won't take much time.

**Comment by wxguy** [comment]
Here is the content of my `environment.yml` file:-

```
# conda env create -f environment.yml  # Create env
# conda env remove -n cmap_test  # Remove env
name: cmap_test
channels:
  - conda-forge
dependencies:
  - python=3.11  
  - conda-forge::libpython-static 
  - conda-forge::wrf-python
  - conda-forge::netcdf4
  - conda-forge::cartopy
  - conda-forge::imageio
  - conda-forge::nuitka
  - conda-forge::ordered-set
  - conda-forge::wrapt
  - conda-forge::patchelf
  - conda-forge::pip
  - conda-forge::metpy
  - conda-forge::pyside6
  - conda-forge::h5py
  - conda-forge::psutil
  - conda-forge::py-cpuinfo
  - conda-forge::distro
  - conda-forge::requests
  - conda-forge::f90nml
  - conda-forge::qtawesome
  - conda-forge::loguru
  - pip:
    - pyinstaller
    - pyqtdarktheme
    - constants
```

Once env is installed and activated using conda activate `cmap_test`, I did:-

`pip install colormaps`

Hopefully, you can reproduce the error on your side.

**Comment by pratiman-91** [comment]
@wxguy Thank you for the `environment.yml` file. I am able to reproduce the `warnings`. It seems like it is not a `colormaps` problem but rather strict standards of `pip` itself.  As these are mere `warnings` you can ignore these. I am working on the workflow for `conda-forge` and it should be available in the upcoming weeks. 

Or if you want to avoid these warnings you can install `PySide6` using `pip install PySide6`.

For more information: [https://stackoverflow.com/questions/67074684/pip-has-problems-with-metadata](https://stackoverflow.com/questions/67074684/pip-has-problems-with-metadata) and [https://gist.github.com/MuhsinFatih/ee0154199803babb449b5bb98d3475f7?permalink_comment_id=4376984](https://gist.github.com/MuhsinFatih/ee0154199803babb449b5bb98d3475f7?permalink_comment_id=4376984).

**Comment by pratiman-91** [comment]
I am closing this is not related to the package.
